### ISSUE TITLE
How do you implement the predict module and where do you use it in spark?

### ISSUE THREAD

**Issue by Lzm1996** [NetX-lab/Elasecutor#2]
Hello,

I'm very interested in this project, and have read you paper. And I'm very interested in your MinFrag algorithm based on DRR and the predict module. But I got some trouble when I try to implement the schedule algorithm, I can't understand the input and the output about the predict algorithm SVR and I did not find you use the predict result in spark code.

thanks,
liuzhangmin

**Comment by LibinLiu0189** [comment]
Thanks for your interests. The input is the configurations for the submitted Spark applications, which includes input data size, resource requirements (CPU and Mem) for each executor, the number of executors, application type, and so on, which are stated in our paper exactly. And the output is the peak resource requirements (e.g., CPU) of each stage for executors and is configuration files to be used for placement calculation and resource allocation of the resource allocation module. You can check resource allocation submodules' logic to see that. If you focus on the scheduling algorithm and want to use the resource profiles as inputs, you can contact me later.

**Comment by Lzm1996** [comment]
Thanks for your answer, Libin.

Can I get a example file of "resprofile"? Because the file for RUD I generated is the pure csv file like "resprofile.csv", and the file can't used to predict. Sorry for bothering you，if it is possible，could you show me the scheduling algorithm and how to use the resource profiles?

Thanks.

**Comment by LibinLiu0189** [comment]
If you mean the file used to report resource utilization from worker to RUD, the resource utilization for CPU is like 200, 200, 200, 200, 200, 100, 100, 100, 100, 100, 100, 150, 150, 150, which includes these stages. This is an example and not the real application's resource utilization. If it is for the scheduler, it is stage1: 200, stage2: 100, and stage3: 150. I don't exactly understand your questions. Do you mean the implementation and real profiles used to do the scheduling? Could you send me your errors of your implementation or the problems reported when you run the codes? Please do not paste them here and send them by email. You can find my email from my github page. Thanks.
